-- MySQL Script generated by MySQL Workbench
-- пн, 08-сер-2022 15:30:34 +0300
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectDb` ;
USE `projectDb` ;

-- -----------------------------------------------------
-- Table `projectDb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDb`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 115
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectDb`.`count_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDb`.`count_product` (
  `count_id` INT NOT NULL AUTO_INCREMENT,
  `count` SMALLINT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`count_id`),
  CONSTRAINT `fk_count_product_1`
    FOREIGN KEY (`count_id`)
    REFERENCES `projectDb`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 115;


-- -----------------------------------------------------
-- Table `projectDb`.`image_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDb`.`image_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_image_product_1`
    FOREIGN KEY (`id`)
    REFERENCES `projectDb`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 115;


-- -----------------------------------------------------
-- Table `projectDb`.`price_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDb`.`price_product` (
  `price_id` INT NOT NULL AUTO_INCREMENT,
  `price` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`price_id`),
  CONSTRAINT `fk_price_product_1`
    FOREIGN KEY (`price_id`)
    REFERENCES `projectDb`.`product` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 115;


-- -----------------------------------------------------
-- Table `projectDb`.`type_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDb`.`type_product` (
  `type_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`type_id`),
  UNIQUE INDEX `Type` (`type` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectDb`.`product_has_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDb`.`product_has_type` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `type_id`),
  INDEX `fk_product_has_type_2_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_product_has_type_1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_type_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `projectDb`.`product` (`id`),
  CONSTRAINT `fk_product_has_type_2`
    FOREIGN KEY (`type_id`)
    REFERENCES `projectDb`.`type_product` (`type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 115
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projectDb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `email` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `password` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `vkey` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `verified` TINYINT(1) NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `projectDb`.`users_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projectDb`.`users_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `surname` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_data_1`
    FOREIGN KEY (`id`)
    REFERENCES `projectDb`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
