<?php

return [
    'bicycle' => [
        ['id' => '1',
            'name' => 'bicycle1',
            'price' => '123',
            'count' => '4',
        ],
        ['id' => '2',
            'name' => 'bicycle2',
            'price' => '333',
            'count' => '53',
        ],
        ['id' => '3',
            'name' => 'bicycle3',
            'price' => '234',
            'count' => '66',
        ],
        ['id' => '4',
            'name' => 'bicycle4',
            'price' => '154',
            'count' => '51',
        ],
        ['id' => '5',
            'name' => 'bicycle5',
            'price' => '342',
            'count' => '4',
        ],
        ['id' => '6',
            'name' => 'bicycle6',
            'price' => '567',
            'count' => '8',
        ],
        ['id' => '7',
            'name' => 'bicycle7',
            'price' => '378',
            'count' => '11',
        ],
        ['id' => '8',
            'name' => 'bicycle8',
            'price' => '444',
            'count' => '15',
        ]
    ],
    'motorcycle' => [
        ['id' => '1',
            'name' => 'motorcycle1',
            'price' => '23423',
            'count' => '52',
        ],
        ['id' => '2',
            'name' => 'motorcycle2',
            'price' => '23333',
            'count' => '123',
        ],
        ['id' => '3',
            'name' => 'motorcycle3',
            'price' => '4666',
            'count' => '44',
        ],
        ['id' => '4',
            'name' => 'motorcycle4',
            'price' => '6435',
            'count' => '65',
        ],
        ['id' => '5',
            'name' => 'motorcycle5',
            'price' => '7888',
            'count' => '77',
        ],
        ['id' => '6',
            'name' => 'motorcycle6',
            'price' => '344',
            'count' => '36',
        ]
    ],
    'car' => [
        ['id' => '1',
            'name' => 'car1',
            'price' => '15544',
            'count' => '32',
        ],
        ['id' => '2',
            'name' => 'car2',
            'price' => '134567',
            'count' => '52',
        ],
        ['id' => '3',
            'name' => 'car3',
            'price' => '1000',
            'count' => '55',
        ],
        ['id' => '4',
            'name' => 'car4',
            'price' => '86444',
            'count' => '33',
        ],
        ['id' => '5',
            'name' => 'car5',
            'price' => '28000',
            'count' => '55',
        ],
    ]
];
